permissions:
  contents: write

name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  win:
    runs-on: windows-2022
    name: Windows VS2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Configure CMake
      run: cmake -B build
    
    - name: Build
      run: |
        cd build
        cmake --build . --config Release
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: Windows x86_64
        path: |
          build/Release/*