permissions:
  contents: write

name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        default: '1.0.0'

jobs:
  win:
    runs-on: windows-2022
    name: Windows VS2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Configure CMake
      run: cmake -B build
    
    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Create zip
      shell: pwsh
      run: Compress-Archive -Path build/Release/* -Destination Windows-msvc-x86_64.zip

    - name: Upload Release as Download
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag }}
        release_name: ${{ github.event.inputs.tag }}
        draft: false
        prerelease: false
        files: |
          Windows-msvc-x86_64.zip